services:
  - type: web
    name: educore
    runtime: dotnet
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/EduCore.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}
